//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sokoban.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exception
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public string Stack { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
