//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sokoban.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solution
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public int LevelIndex { get; set; }
        public int Moves { get; set; }
        public int Pushes { get; set; }
        public int Time { get; set; }
    
        public virtual User User { get; set; }
    }
}
